### ISSUE TITLE
New login email

### ISSUE THREAD

**Issue by JElgar** [now-u/now-u-campaigns#109]
Description:
**As a:** user
**Currently**: the login token is a long horrible thing
**I want:** it to be a 6 digit code
**Because:** so I can easily type it in even if I don't know copying is a thing

Reporter:
Stephan Ellenberger 

Trello link:
https://trello.com/c/ynBBAiKZ/245-new-login-email

Comments:
Your welcome! And that works :) @jameselgar,Again that's perfect thank you so much @stinaovaskainen. I think we can probably just the the basic copy and if we find its not clear enough we can always add more!
,Hi @jameselgar So I added another two options above, that brings out the code more and two options of the explanation copy (one deeper and one simpler). What do you think? :) ,Hi @stinaovaskainen this looks perfect! If the 2nd CTA did anything it would have to be copying the code (as we wouldnt be able to open the app for them automatically because if we could they would just use the top link). If we can't get copying working for the button then we can just take out the 2nd CTA for now and keep the rest as is. 
In terms of the code I think you are absolutely right about having the main CTA above the code. Would it be possible however to have the code centered and on its own line (and maybe even a bigger font) just to make it a bit clearer? So something like

Or use this secret code in the app to log in:
                      **123456**,Hi @jameselgar So I adde another option with a mobile and desktop version. If logging in is the preferred and easy path I would have that first and then the 'if that didn't work token section, I added a secondary CTA for that (you might need to double check that works with the brand). Also I don't have the white logo, but you can replace it if you have an orange version of it that would work? :) Generally for mobile emails if possible it's best to have edge to edge CTAs so I added that for it here. And there are ways to highlight the code, here I made it bold but another option to add to it if needed would be an underline. ,Hi @stinaovaskainen thank you so much for this, that looks great but a few points
1. Could the token section be a bit more prevalent? So atm one of the issues with the email is the token is a bit hidden but I think for this it would be good if the user saw the token regardless of whether they used the link or not. Maybe the token could be above the button and the copy could just be something like "here is your secret code", then if the user does click the link and it fails then they will know that the code was there and use that instead (whereas atm they just don't seem to know a token is an option)
2. Sorry you are so right but MailChimp was a bit of a red herring, we use that for all the marketing stuff but we do write this email in html so we can have media queries and stuff for web/mobile
3. Could we use the other logo style (the one in the current email; colour can change), Im not really sure the logic to which we use but I think that one is mostly just used for the app icon atm and imo the other one is just betterer but if you think otherwise please do say,Hi @jameselgar So I added a rough version of the mobile email, is that the type of copy you were thinking for it? Or keep it similar to the current one with an update for the token one? If your using mail-chimp, then you would likely only be able to do 1 design, so I'm happy to stick to the mobile first for now? :) ,Hello! So this is the only service email we send out but I can send over some example emails we send out for marketing if that helps (these arent necessarily great examples tho as they are limited by what the free mailchimp plan offers)? 
In terms of desktop and mobile. The priority is definitely mobile (as this link doesn't work off mobile). However, if you are happy to also do a desktop version as well that would be amazing. This is because we could then reuse this email for when a user is logging into the website in the future.,Hi @jameselgar Just checking, can you add any other types of service email emails that you do? So I can check the style and layout match. Also do you design for mobile and desktop or just one (ie in my day job we do both so that the desktop one resizes for mobile, areas condense and shift plus cta gets bigger etc)?

**Comment by stellenberger** [comment]
This is now a PR in the API repository
