### ISSUE TITLE
Website Metadata updates

### ISSUE THREAD

**Issue by JElgar** [now-u/now-u-campaigns#26]
- [ ] Add previews on social media

- [x] Update preview text for google search

- [x] Add image labels (when the image doesn't load this shows but also helps seo)

**Comment by JElgar** [comment]
When updating content chat to [Will](https://now-u.slack.com/archives/D013ZV3P5FW) for what to put

**Comment by stellenberger** [comment]
Updates on this issue: 

The description on google search has been fixed from the Google Analytics PR
