### ISSUE TITLE
Now-u newsletter popup

### ISSUE THREAD

**Issue by JElgar** [now-u/now-u-campaigns#33]
After approx 30 seconds of being on the website, a popup should be shown to sign up for our newsletter. The form should be implemented using mail chimp (it was in v2). Designs are in XD

**Comment by stellenberger** [comment]
![Web- pop up](https://user-images.githubusercontent.com/53180713/87850791-d7fff600-c8ea-11ea-9e2b-8c767b9c9634.png)

**Comment by ArronAult** [comment]
Some questions:

What to do if a user has already signed up?
What to do if a user has already closed the pop-up before?

Do we utilise cookies or local storage currently?

**Comment by JElgar** [comment]
Currently, we have no concept of sessions. In the future, we will probably have user login on the site so they can interact with campaigns and comment on blogs post etc. Not having a concept of session will make the first two points rather tricky but its a very good point, I guess for now we'll have to show it after 30s every time someone launches the site. I think this should apply to any page, so for now if the user changes route we will still do the pop-up. If this adds more work then lets trail the popup on the home page first so we can be sure it's actually something we want then we can make the timer persist across all pages if we like it. If its easy enough to apply to all routes from the get go then let's just do that straight away

**Comment by ArronAult** [comment]
@JElgar 
> 
> 
> Currently, we have no concept of sessions. In the future, we will probably have user login on the site so they can interact with campaigns and comment on blogs post etc. For now, not having a concept of session will make the first two points rather tricky but its a very good point, I guess for now we'll have to show it after 30s every time someone launches the site. I think this should apply to any page, so for now if the user changes route we will still do the pop-up. If this adds more work then lets trail the popup on the home page first so we can be sure it's actually something we want then we can make the timer persist across all pages if we like it. If its easy enough to apply to all routes from the get go then let's just do that straight away

I had a look into the options and cookies seem suitable with the use of [universal-cookie](https://github.com/reactivestack/cookies/tree/master/packages/universal-cookie). We could use session (when the browser closes the session ends) expiry cookies for if a user dismisses the modal and some big number (1 year) expiry for if a user successfully signs up to the newsletter.

If we put the modal instantiation in some persistant component (haven't investigated it yet so unsure on the lifecycles) like the header navbar it should be clean to have it site-wide.

**Comment by JElgar** [comment]
One issue to note is our privacy policy says we don't use any cookies (other than those provided by google analytics and Facebook pixel) so this is something we would have to update. If we can I want to avoid having to get people to consent to things as that just an extra barrier to entering the site. Cookies for this purpose really shouldn't be an issue tho as far as im aware (its something worth double-checking tho).

Might also be worth checking if there is a simpler way of doing this? There seem to be some nice solutions listed here: 
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage

**Comment by JElgar** [comment]
What do you think about this option?
https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API

**Comment by ArronAult** [comment]
@JElgar 

Good point about privacy. I had a look into local and session storage before and they seem suitable also. I'll see if I can get it working today

**Comment by stellenberger** [comment]
Here are the updated designs for the success message! 
![Web- pop up – 1](https://user-images.githubusercontent.com/53180713/89201278-24188f00-d5a9-11ea-863e-5c22fb97e2c4.png)
