### ISSUE TITLE
Home page design update

### ISSUE THREAD

**Issue by JElgar** [now-u/now-u-campaigns#37]
Update the home page to match new v3 designs

**Comment by stellenberger** [comment]
![homev12](https://user-images.githubusercontent.com/53180713/88955067-4fdb0280-d293-11ea-8e75-e2acdff4340e.png)
![homev12mobile](https://user-images.githubusercontent.com/53180713/88955079-549fb680-d293-11ea-9c93-0c3fbc7aced2.png)

**Comment by tunangst** [comment]
Are our partners on the backend that I can fetch or am I creating them?
I can't seem to find where our api targets are.

I may be wrong but it looks like our live web app is using links to websites for the images which I rather not do in case someone decides to change that image to something inappropriate. 

If I am creating the partners cards inline and we are saving them to our assets, would you want me to do so or one of the designers?

**Comment by JElgar** [comment]
Had a quick chat and just to keep a record heres the outcome: 

1. Found API call for partners here: https://github.com/now-u/now-u-campaigns/blob/dev/src/domain/home/Homepage.jsx

Uses 
```
const [partners, setPartners] = useState([]);
const fetchPartners = async () => {
      const respPartners = await fetch('https://api.now-u.com/api/v1/organisations');
      const partners = await respPartners.json();
      setPartners(partners?.data);
    };
    fetchPartners();
```

2. You are completely right about the image links being very bad. The solution here is to replace the image links with links to somewhere we host them ourselves (@MaximeRobeyns recommended bunny cdn which looks pretty noice and s3 is another obvious choice as well)
