### ISSUE TITLE
Google play button squashed dimensions

### ISSUE THREAD

**Issue by JElgar** [now-u/now-u-campaigns#51]
Description:
The google play button is scaled weirdly and isn't the correct dimensions. I have attached screenshots of what it should look like and what it currently looks like on the site.

Reporter:
James Elgar 

Trello link:
https://trello.com/c/C5v7bfKp/139-google-play-button-squashed-dimensions

Comments:

**Comment by tunangst** [comment]
Hello, can I be invited to see the Trello link please. :]

**Comment by tunangst** [comment]
Since the images don't have the same aspect ratio, so the horizontal scaling will not work. I will have to change the flex scaling or edit the image.

**Comment by JElgar** [comment]
Sorry @tunangst you should be invited now!

**Comment by JElgar** [comment]
Is it possible to keep the height the same and then allow the images to scale to whatever width they need to keep the current aspect ratio? (ie the height is the same but the width is different)

**Comment by tunangst** [comment]
Thank you. Yes, I think that will be best.
