### ISSUE TITLE
Success state after signing up for news letter

### ISSUE THREAD

**Issue by JElgar** [now-u/now-u-campaigns#56]
Description:
**As a:** user of the website tyring to sign up for the newletter
**Currently**: I have no indication whether the signup request has been successful
**I want:** An indicator to show the new letter signup has been successful
**Because:** To know whether the request to join the newsletter has been successful

Reporter:
James Elgar 

Trello link:
https://trello.com/c/a4rR3VYZ/150-success-state-after-signing-up-for-news-letter

Comments:

**Comment by stellenberger** [comment]
I have assigned Arron to this as to avoid confusion/no one else accidentally does this as its already in progress.
