### ISSUE TITLE
Add second header/navbar that displays the FAQ Blog and Newsletter

### ISSUE THREAD

**Issue by JElgar** [now-u/now-u-campaigns#61]
Description:

Reporter:
Stephan Ellenberger 

Trello link:
https://trello.com/c/5x1bpAaB/165-add-second-header-navbar-that-displays-the-faq-blog-and-newsletter

Comments:

**Comment by stellenberger** [comment]
![Screenshot 2020-07-30 at 18 40 53](https://user-images.githubusercontent.com/53180713/88955726-38504980-d294-11ea-8eb1-db3954246dd6.png)

**Comment by stellenberger** [comment]
![Screenshot 2020-07-30 at 18 41 31](https://user-images.githubusercontent.com/53180713/88955777-4e5e0a00-d294-11ea-8e56-ffcb1c9e91a7.png)

**Comment by stellenberger** [comment]
Please notice that this issue only applies to any device where the menu spans the whole page - all mobile devices or screen sizes where the menu turns into a burger icon - shove all the links together.

**Comment by JElgar** [comment]
Ah yes, good spot! Lets keep the privacy policy just in the bottom nav bar.
