### ISSUE TITLE
Text not visible in login email

### ISSUE THREAD

**Issue by JElgar** [now-u/now-u-campaigns#67]
Description:
**Describe the bug**
The text is white on a white background on the login email

**To Reproduce**
1. Open signup email in yahoo mail

**Expected behavior**
For background to be orange gradient and text to be white

**Screenshots**

**Smartphone (please complete the following information):**
Yahoo Mail web client

**Additional context**

Reporter:
James Elgar 

Trello link:
https://trello.com/c/34aZ0C0h/151-text-not-visible-in-login-email

Comments:
Yes thats perfect! ,@stephanellenberger I'm thinking of making this a web-team problem. Would that be all right with you? (We can talk specifics eg where should we store the code for this email)

**Comment by stellenberger** [comment]
This issue has a PR in now-u-api.
