### ISSUE TITLE
v3 design variable update

### ISSUE THREAD

**Issue by tunangst** [now-u/now-u-campaigns#76]
Keep in mind, changing the variable name will break the pages invoking the name.
I will post the designs when I obtain them.

**Comment by JElgar** [comment]
Sorry, I'm confused. Is this updating the Sass variables in some way?

**Comment by tunangst** [comment]
Yes, it does sound confusing.
In my head, I was thinking of things being more consistent (I know everything will not be 100% the same). 
We have several different shadow angles, the colors are kind of confusing me looking at a glob of them, Nunito isn't just used as a body font anymore, Rockwell has never worked for me, it defaults to serif. I have almost always had to adjust my Text component font size.
If things were more reusable, it would help me, at least, from customizing several things.
