### ISSUE TITLE
Campaigns title overflows into header

### ISSUE THREAD

**Issue by JElgar** [now-u/now-u-campaigns#88]
Description:

Reporter:
Stephan Ellenberger 

Trello link:
https://trello.com/c/rAe3sIyG/236-campaigns-title-overflows-into-header

Comments:

**Comment by stellenberger** [comment]
![Screenshot 2020-08-24 at 19 59 40](https://user-images.githubusercontent.com/53180713/91154006-da5b2a00-e6b8-11ea-80e1-d85331242a74.png)
